version: '3.9'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./docker/go
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - .:/opt/app
    network_mode: host
