version: '3.9'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./docker/go
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - .:/opt/app
    ports:
      - "9090:9090"
    network_mode: host
